# Generated by Django 3.1.6 on 2022-11-30 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='baslik')),
                ('content', models.TextField(verbose_name='icerik')),
                ('price', models.IntegerField(verbose_name='fiyat')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='ilan_tarihi')),
                ('address', models.CharField(max_length=40, verbose_name='adres')),
                ('phone', models.IntegerField(verbose_name='telefon')),
                ('image', models.ImageField(upload_to='files/covers', verbose_name='fotograf')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ilan_sahibi')),
            ],
        ),
    ]
