# Generated by Django 3.1.6 on 2022-11-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0002_auto_20221130_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='image',
            field=models.ImageField(default='', upload_to='files/covers', verbose_name='fotograf'),
            preserve_default=False,
        ),
    ]
