# Generated by Django 3.1.6 on 2022-12-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0004_auto_20221202_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='address',
            field=models.CharField(choices=[('tekirdag', 'Tekirdağ'), ('bursa', 'Bursa'), ('kocaeli', 'Kocaeli')], max_length=15),
        ),
    ]
