# Generated by Django 3.1.6 on 2022-12-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0005_auto_20221203_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='gender',
            field=models.CharField(choices=[('m', 'Erkek'), ('f', 'Dişi')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
