# Generated by Django 3.1.6 on 2022-12-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0006_ilan_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='age',
            field=models.CharField(choices=[('0-3 Aylık', '0-3 Aylık'), ('3-6 Aylık', '3-6 Aylık'), ('6-12 Aylık', '6-12 Aylık'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9 ve Üstü', '9 ve Üstü')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ilan',
            name='address',
            field=models.CharField(choices=[('Tekirdağ', 'Tekirdağ'), ('Bursa', 'Bursa'), ('Kocaeli', 'Kocaeli')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='gender',
            field=models.CharField(choices=[('Erkek', 'Erkek'), ('Dişi', 'Dişi')], max_length=15),
        ),
    ]
